name: Publish on FlakeHub
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          upload-name: edolstra/blender-bin
          directory: blender-bin
